services:
  - type: web
    name: whatsapp-is-hotel-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --bind 0.0.0.0:$PORT --timeout 120 --preload
    plan: free
